<?php

namespace ShipBundle\Repository;

/**
 * CannonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CannonRepository extends \Doctrine\ORM\EntityRepository
{
}
